name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cli:
    name: Build CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            folder: linux-x64
            bin_name: ano7
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            folder: win32-x64
            bin_name: ano7.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            folder: darwin-x64
            bin_name: ano7
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   folder: darwin-arm64
          #   bin_name: ano7
          # Uncomment above for M1 support when self-hosted or supported runner available/configured

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --target ${{ matrix.target }} --bin ano7

    - name: Prepare Artifact
      shell: bash
      run: |
        mkdir -p dist/${{ matrix.folder }}
        cp target/${{ matrix.target }}/release/${{ matrix.bin_name }} dist/${{ matrix.folder }}/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cli-binaries
        path: dist/*

  package-extension:
    needs: build-cli
    name: Package Extension
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Download CLI Binaries
      uses: actions/download-artifact@v3
      with:
        name: cli-binaries
        path: frontends/vscode-ao7/bin

    - name: Install dependencies
      working-directory: frontends/vscode-ao7
      run: npm ci

    - name: Package VSIX
      working-directory: frontends/vscode-ao7
      run: npx vsce package --out ao7.vsix

    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: frontends/vscode-ao7/ao7.vsix
